# Generated by Django 5.2.9 on 2026-01-13 18:02

import apps.common.utils.files.files
import apps.common.utils.validators
import core.storages
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, storage=core.storages.PublicMediaStorage(), upload_to=apps.common.utils.files.files.unique_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), apps.common.utils.validators.validate_image_size]),
        ),
    ]
