# Generated by Django 6.0.1 on 2026-01-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(max_length=30)),
                ('logger_name', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('pathname', models.CharField(blank=True, max_length=500, null=True)),
                ('line_no', models.IntegerField(blank=True, null=True)),
                ('exception', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Log Entry',
                'verbose_name_plural': 'Log Entries',
                'db_table': 'Log_entry',
            },
        ),
    ]
