# Generated by Django 6.0.1 on 2026-01-15 06:03

import apps.common.utils.files.files
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('news', 'News'), ('announcement', 'Official Announcement'), ('report', 'Report'), ('media', 'Media/Video')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Post Category',
                'verbose_name_plural': 'Post Categories',
                'db_table': 'PostCategories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('short_description', models.TextField(blank=True, help_text='Brief description or excerpt')),
                ('content', models.TextField(blank=True, help_text='Main content of the post')),
                ('image', models.ImageField(blank=True, help_text='Featured image or thumbnail', null=True, upload_to=apps.common.utils.files.files.unique_image_path)),
                ('video_url', models.URLField(blank=True, help_text='YouTube or external video URL', max_length=500, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('type_tag', models.CharField(blank=True, help_text="Additional type tag (e.g., 'Education', 'Technology')", max_length=50)),
                ('views_count', models.BigIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.postcategory')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'Posts',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'published_at'], name='Posts_status_c4e579_idx'), models.Index(fields=['category', 'status'], name='Posts_categor_34c798_idx'), models.Index(fields=['slug'], name='Posts_slug_5a2469_idx')],
            },
        ),
    ]
