# Generated by Django 6.0.1 on 2026-01-17 22:22

import apps.common.utils.files.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='content_en',
            field=models.TextField(blank=True, help_text='Main content (English)'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ru',
            field=models.TextField(blank=True, help_text='Main content (Russian)'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_uz',
            field=models.TextField(blank=True, help_text='Main content (Uzbek)'),
        ),
        migrations.AddField(
            model_name='post',
            name='short_description_en',
            field=models.TextField(blank=True, help_text='Brief description (English)'),
        ),
        migrations.AddField(
            model_name='post',
            name='short_description_ru',
            field=models.TextField(blank=True, help_text='Brief description (Russian)'),
        ),
        migrations.AddField(
            model_name='post',
            name='short_description_uz',
            field=models.TextField(blank=True, help_text='Brief description (Uzbek)'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (English)'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (Russian)'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_uz',
            field=models.CharField(default='', max_length=255, verbose_name='Title (Uzbek)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video file (use either URL or file, not both)', null=True, upload_to=apps.common.utils.files.files.unique_video_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube or external video URL (use either URL or file, not both)', max_length=500, null=True),
        ),
    ]
